# Generated by Django 3.2.18 on 2023-04-16 00:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import glosowania.models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decyzja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Enter short title describing new law.', max_length=200, null=True, verbose_name='Title')),
                ('tresc', models.TextField(help_text='Enter the exact wording of the law as it is to be applied.', max_length=500, null=True, verbose_name='Law text')),
                ('kara', models.TextField(help_text='What is the penalty for non-compliance with this rule. This can be, for example: "Banishment for 3 months", "Banishment forever", etc.', max_length=500, null=True, verbose_name='Penalty for non-compliance')),
                ('uzasadnienie', models.TextField(help_text='What events inspired this bill? What are we going to achieve with it?', max_length=1500, null=True, verbose_name='Reasoning')),
                ('args_for', models.TextField(help_text='Enter the benefits for the group, environment, economy, etc. resulting from the introduction of the idea.', max_length=1500, null=True, verbose_name='Positive Aspects of the Idea')),
                ('args_against', models.TextField(help_text='Enter the potential threat associated with the proposal.', max_length=1500, null=True, verbose_name='Negative Aspects of the Idea')),
                ('znosi', models.CharField(blank=True, help_text='If the proposed law supersedes other bills, enter their comma separated numbers here.', max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.'), glosowania.models.does_it_exist], verbose_name='Abolishes the rules')),
                ('ile_osob_podpisalo', models.SmallIntegerField(default=0, editable=False)),
                ('data_powstania', models.DateField(auto_now_add=True, null=True)),
                ('data_zebrania_podpisow', models.DateField(editable=False, null=True)),
                ('data_referendum_start', models.DateField(editable=False, null=True)),
                ('data_referendum_stop', models.DateField(editable=False, null=True)),
                ('data_zatwierdzenia', models.DateField(editable=False, null=True)),
                ('data_obowiazuje_od', models.DateField(editable=False, null=True)),
                ('za', models.SmallIntegerField(default=0, editable=False)),
                ('przeciw', models.SmallIntegerField(default=0, editable=False)),
                ('status', models.SmallIntegerField(default=1, editable=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, null=True)),
                ('vote', models.BooleanField(editable=False, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glosowania.decyzja')),
            ],
        ),
        migrations.CreateModel(
            name='ZebranePodpisy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podpis_uzytkownika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glosowania.decyzja')),
            ],
            options={
                'unique_together': {('projekt', 'podpis_uzytkownika')},
            },
        ),
        migrations.CreateModel(
            name='KtoJuzGlosowal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktory_uzytkownik_juz_zaglosowal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glosowania.decyzja')),
            ],
            options={
                'unique_together': {('projekt', 'ktory_uzytkownik_juz_zaglosowal')},
            },
        ),
    ]
