# Generated by Django 3.2.18 on 2023-12-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decyzja',
            name='path',
            field=models.CharField(max_length=1000, null=True, verbose_name='The path this bill took.'),
        ),
        migrations.AlterField(
            model_name='decyzja',
            name='tresc',
            field=models.TextField(help_text='Enter the exact wording of the law as it is to be applied.', max_length=1000, null=True, verbose_name='Law text'),
        ),
    ]
