# Generated by Django 3.2.18 on 2023-12-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0002_auto_20231217_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decyzja',
            name='data_obowiazuje_od',
        ),
        migrations.RemoveField(
            model_name='decyzja',
            name='data_zatwierdzenia',
        ),
    ]
