# Generated by Django 5.0.6 on 2025-04-29 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0003_auto_20231217_1932'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ktojuzglosowal',
            name='ktory_uzytkownik_juz_zaglosowal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zebranepodpisy',
            name='podpis_uzytkownika',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zebranepodpisy',
            name='projekt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='glosowania.decyzja'),
        ),
    ]
