# Generated by Django 5.0.6 on 2025-04-29 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0004_alter_ktojuzglosowal_ktory_uzytkownik_juz_zaglosowal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ktojuzglosowal',
            name='ktory_uzytkownik_juz_zaglosowal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
