# Generated by Django 5.0.6 on 2025-07-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0005_alter_ktojuzglosowal_ktory_uzytkownik_juz_zaglosowal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decyzja',
            name='uzasadnienie',
            field=models.TextField(help_text='What events or thoughts inspired this bill? What are the axpected results?', max_length=1500, null=True, verbose_name='Reasoning'),
        ),
    ]
