# Generated by Django 5.0.6 on 2025-07-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0006_alter_decyzja_uzasadnienie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decyzja',
            name='uzasadnienie',
            field=models.TextField(help_text='What events or thoughts inspired this bill? What are the expected results?', max_length=1500, null=True, verbose_name='Reasoning'),
        ),
    ]
