# Generated by Django 5.2.9 on 2026-01-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0007_alter_decyzja_uzasadnienie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decyzja',
            name='uzasadnienie',
            field=models.TextField(help_text='What events or thoughts inspired this bill? What are the expected results?', max_length=2000, null=True, verbose_name='Reasoning'),
        ),
    ]
