# Generated by Django 5.2.9 on 2026-01-17 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0008_alter_decyzja_uzasadnienie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument_type', models.CharField(choices=[('FOR', 'Positive'), ('AGAINST', 'Negative')], help_text='Is this a positive or negative argument?', max_length=10, verbose_name='Argument Type')),
                ('content', models.TextField(help_text='Enter your argument. You can include links.', max_length=1000, verbose_name='Argument Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('decyzja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='glosowania.decyzja', verbose_name='Decision')),
            ],
            options={
                'verbose_name': 'Argument',
                'verbose_name_plural': 'Arguments',
                'ordering': ['created_at'],
            },
        ),
    ]
