# Generated by Django 5.2.9 on 2026-01-17 16:07

from django.db import migrations


def migrate_arguments_to_new_model(apps, schema_editor):
    """
    Migrate existing args_for and args_against text fields to Argument model.
    Each non-empty field will create one Argument record.
    """
    Decyzja = apps.get_model('glosowania', 'Decyzja')
    Argument = apps.get_model('glosowania', 'Argument')
    
    for decyzja in Decyzja.objects.all():
        # Migrate args_for (positive arguments)
        if decyzja.args_for and decyzja.args_for.strip():
            Argument.objects.create(
                decyzja=decyzja,
                author=decyzja.author,
                argument_type='FOR',
                content=decyzja.args_for.strip(),
                # created_at and modified_at will be set automatically
            )
        
        # Migrate args_against (negative arguments)
        if decyzja.args_against and decyzja.args_against.strip():
            Argument.objects.create(
                decyzja=decyzja,
                author=decyzja.author,
                argument_type='AGAINST',
                content=decyzja.args_against.strip(),
                # created_at and modified_at will be set automatically
            )


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: copy first Argument of each type back to text fields.
    This is a lossy operation if there are multiple arguments.
    """
    Decyzja = apps.get_model('glosowania', 'Decyzja')
    Argument = apps.get_model('glosowania', 'Argument')
    
    for decyzja in Decyzja.objects.all():
        # Get first positive argument
        positive_arg = Argument.objects.filter(
            decyzja=decyzja,
            argument_type='FOR'
        ).first()
        if positive_arg:
            decyzja.args_for = positive_arg.content
        
        # Get first negative argument
        negative_arg = Argument.objects.filter(
            decyzja=decyzja,
            argument_type='AGAINST'
        ).first()
        if negative_arg:
            decyzja.args_against = negative_arg.content
        
        decyzja.save()


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0009_argument'),
    ]

    operations = [
        migrations.RunPython(
            migrate_arguments_to_new_model,
            reverse_migration
        ),
    ]
