# Generated by Django 5.2.9 on 2026-01-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0010_migrate_arguments_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='decyzja',
            name='data_ostatniej_modyfikacji',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
