# Generated by Django 5.2.9 on 2026-02-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glosowania', '0011_decyzja_data_ostatniej_modyfikacji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decyzja',
            name='uzasadnienie',
            field=models.TextField(help_text='Why do we need this law? What events or thoughts inspired this bill? What are the expected results?', max_length=2000, null=True, verbose_name='Reasoning'),
        ),
    ]
