# Generated by Django 6.0.3 on 2026-04-08 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('glosowania', '0012_alter_decyzja_uzasadnienie'),
    ]

    operations = [
        migrations.AddField(
            model_name='decyzja',
            name='chat_room',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='decyzja',
                to='chat.room',
                verbose_name='chat room'
            ),
        ),
    ]
