# Generated by Django 5.0.6 on 2025-09-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, help_text='Link to event details, registration, or location'),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, help_text='Event location or venue', max_length=200),
        ),
    ]
