# Generated by Django 5.0.6 on 2025-09-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_link_event_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the event', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='When does the event end? (optional)', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='frequency',
            field=models.CharField(choices=[('once', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='once', help_text='How often does this event repeat?', max_length=10, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to disable this event', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link to event details, registration, or location', verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, help_text='Optional event location or venue', max_length=200, verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(help_text='When does the event start?', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Enter a descriptive name for the event', max_length=200, verbose_name='Title'),
        ),
    ]
