# Generated by Django 5.0.6 on 2025-10-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_description_alter_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Public events are visible to everyone. Private events are only visible to logged-in users.', verbose_name='Public'),
        ),
    ]
