# Generated by Django 5.0.6 on 2025-10-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='monthly_ordinal',
            field=models.IntegerField(blank=True, choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (-1, 'Last')], help_text='For monthly ordinal events: which week? (e.g., First, Second, Last)', null=True, verbose_name='Week of month'),
        ),
        migrations.AddField(
            model_name='event',
            name='monthly_weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='For monthly ordinal events: which day of the week? (e.g., Monday, Tuesday)', null=True, verbose_name='Day of week'),
        ),
        migrations.AlterField(
            model_name='event',
            name='frequency',
            field=models.CharField(choices=[('once', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('monthly_ordinal', 'Monthly (specific weekday)'), ('yearly', 'Yearly')], default='once', help_text='How often does this event repeat?', max_length=20, verbose_name='Frequency'),
        ),
    ]
