# Generated by Django 5.2.9 on 2026-01-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_monthly_ordinal_event_monthly_weekday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link to event details, registration, or location', verbose_name='Link do spotkania'),
        ),
    ]
