# Generated by Django 5.0.6 on 2024-09-14 08:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obywatele', '0006_remove_uzytkownik_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True, verbose_name='Symbol')),
                ('validity', models.IntegerField(blank=True, default=0, help_text='Validity in days. If unlimited then 0', null=True, verbose_name='Validity')),
                ('notes', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone')),
                ('web_page', models.URLField(blank=True, null=True, verbose_name='Web page')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('uzytkownik', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='obywatele.uzytkownik', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('payment_deadline', models.DateField(blank=True, default=datetime.datetime.now, editable=False, null=True, verbose_name='Deadline')),
                ('payment_received', models.BooleanField(default=False, verbose_name='Payment received')),
                ('outgoing_amount', models.FloatField(null=True, verbose_name='Outgoing amount')),
                ('incoming_amount', models.FloatField(null=True, verbose_name='Incoming amount')),
                ('is_signed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is signed')),
                ('for_year', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='For year')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Note')),
                ('associate_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='associate_from', to='bookkeeping.associate', verbose_name='Associate from')),
                ('associate_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='associate_to', to='bookkeeping.associate', verbose_name='Associate to')),
                ('incoming_asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='incoming_asset', to='bookkeeping.asset', verbose_name='Incoming asset')),
                ('outgoing_asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='outgoing_asset', to='bookkeeping.asset', verbose_name='Outgoing asset')),
                ('sideA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_entries', to='obywatele.uzytkownik', verbose_name='SideA')),
                ('sideB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_entries', to='obywatele.uzytkownik', verbose_name='SideB')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookkeeping.associate', verbose_name='Storage')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('year', models.DateField(blank=True, null=True, verbose_name='Year')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookkeeping.asset')),
                ('associate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookkeeping.associate')),
            ],
        ),
        migrations.AddField(
            model_name='associate',
            name='assets',
            field=models.ManyToManyField(through='bookkeeping.Report', to='bookkeeping.asset', verbose_name='Asset'), # type: ignore
        ),
    ]
