# Generated by Django 5.0.6 on 2024-11-17 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0001_initial'),
        ('obywatele', '0006_remove_uzytkownik_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='uzytkownik',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obywatele.uzytkownik', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='report',
            name='associate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookkeeping.associate'),
        ),
    ]
