# Generated by Django 5.0.6 on 2024-11-17 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0002_alter_associate_uzytkownik_alter_report_associate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookkeeping.asset'),
        ),
    ]
