# Generated by Django 5.0.6 on 2025-04-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0003_alter_report_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='payment_deadline',
            new_name='payment_received_date',
        ),
    ]
