# Generated by Django 5.0.6 on 2025-04-13 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0005_alter_entry_payment_received_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='payment_received_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Payment received date'),
        ),
    ]
