# Generated by Django 5.0.6 on 2025-04-13 14:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0006_alter_entry_payment_received_date'),
        ('obywatele', '0007_alter_uzytkownik_last_broadcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('payment_received_date', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Payment received date')),
                ('is_signed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is signed')),
                ('payment_received', models.BooleanField(default=False, verbose_name='Payment received')),
                ('for_year', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='For year')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Note')),
                ('incoming_amount', models.FloatField(null=True, verbose_name='Incoming amount')),
                ('associate_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='incoming_transactions', to='bookkeeping.associate', verbose_name='Associate to')),
                ('incoming_asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='incoming_assets', to='bookkeeping.asset', verbose_name='Incoming asset')),
                ('sideA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_incoming_transactions', to='obywatele.uzytkownik', verbose_name='SideA')),
                ('sideB', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_incoming_transactions', to='obywatele.uzytkownik', verbose_name='SideB')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Outgoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('payment_received_date', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Payment received date')),
                ('is_signed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is signed')),
                ('payment_received', models.BooleanField(default=False, verbose_name='Payment received')),
                ('for_year', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='For year')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Note')),
                ('outgoing_amount', models.FloatField(null=True, verbose_name='Outgoing amount')),
                ('associate_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='outgoing_transactions', to='bookkeeping.associate', verbose_name='Associate from')),
                ('outgoing_asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='outgoing_assets', to='bookkeeping.asset', verbose_name='Outgoing asset')),
                ('related_incoming', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_outgoing', to='bookkeeping.incoming', verbose_name='Related incoming')),
                ('sideA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_outgoing_transactions', to='obywatele.uzytkownik', verbose_name='SideA')),
                ('sideB', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_outgoing_transactions', to='obywatele.uzytkownik', verbose_name='SideB')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
