# Generated by Django 5.0.6 on 2025-04-13 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0007_incoming_outgoing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming',
            name='associate_to',
        ),
        migrations.RemoveField(
            model_name='outgoing',
            name='associate_from',
        ),
        migrations.AddField(
            model_name='incoming',
            name='associate_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='incoming_transactions', to='bookkeeping.associate', verbose_name='Associate from'),
        ),
        migrations.AddField(
            model_name='outgoing',
            name='associate_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='outgoing_transactions', to='bookkeeping.associate', verbose_name='Associate to'),
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
