# Generated by Django 5.0.6 on 2025-04-13 16:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0008_remove_incoming_associate_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoing',
            name='related_incoming',
        ),
        migrations.RemoveField(
            model_name='outgoing',
            name='associate_to',
        ),
        migrations.RemoveField(
            model_name='outgoing',
            name='outgoing_asset',
        ),
        migrations.RemoveField(
            model_name='outgoing',
            name='sideA',
        ),
        migrations.RemoveField(
            model_name='outgoing',
            name='sideB',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('payment_received_date', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Payment received date')),
                ('payment_deadline_date', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Payment deadline date')),
                ('is_signed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is signed')),
                ('payment_received', models.BooleanField(default=False, verbose_name='Payment received')),
                ('for_year', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='For year')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Note')),
                ('amount', models.FloatField(null=True, verbose_name='Outgoing amount')),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='outgoing_assets', to='bookkeeping.asset', verbose_name='Outgoing asset')),
                ('associate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='outgoing_transactions', to='bookkeeping.associate', verbose_name='Associate')),
            ],
        ),
        migrations.DeleteModel(
            name='Incoming',
        ),
        migrations.DeleteModel(
            name='Outgoing',
        ),
    ]
