# Generated by Django 5.0.6 on 2025-04-13 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0009_remove_outgoing_related_incoming_and_more'),
        ('obywatele', '0007_alter_uzytkownik_last_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('I', 'Incoming'), ('O', 'Outgoing')], default='I', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='uzytkownik',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='obywatele.uzytkownik', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='report',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookkeeping.asset'),
        ),
        migrations.AlterField(
            model_name='report',
            name='associate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookkeeping.associate'),
        ),
    ]
