# Generated by Django 5.0.6 on 2025-04-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0010_transaction_type_alter_associate_uzytkownik_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_signed',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_received',
        ),
    ]
