# Generated by Django 5.0.6 on 2025-04-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0011_remove_transaction_is_signed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='for_year',
        ),
    ]
