# Generated by Django 5.0.6 on 2025-04-13 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0012_remove_transaction_for_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='associate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.associate'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='associate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='bookkeeping.associate', verbose_name='Associate'),
        ),
    ]
