# Generated by Django 5.0.6 on 2025-04-13 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0013_alter_report_associate_alter_transaction_associate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associate',
            name='assets',
        ),
    ]
