# Generated by Django 5.0.6 on 2025-04-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0014_remove_associate_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='assets',
            field=models.ManyToManyField(through='bookkeeping.Report', to='bookkeeping.asset', verbose_name='Asset'),
        ),
    ]
