# Generated by Django 5.0.6 on 2025-04-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0015_associate_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associate',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='associate',
            name='uzytkownik',
        ),
    ]
