# Generated by Django 5.0.6 on 2025-04-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0018_category_currency_remove_report_asset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
