# Generated by Django 5.0.6 on 2025-04-13 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0019_remove_transaction_currency_delete_currency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Associate',
            new_name='Partner',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='associate',
            new_name='partner',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='associate',
        ),
        migrations.AddField(
            model_name='transaction',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.partner', verbose_name='Partner'),
        ),
    ]
