# Generated by Django 5.0.6 on 2025-04-13 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0020_rename_associate_partner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
