# Generated by Django 5.0.6 on 2025-04-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0021_delete_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='web_page',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Web page'),
        ),
    ]
