# Generated by Django 5.0.6 on 2025-03-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
