# Generated by Django 5.0.6 on 2025-04-29 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_room_alter_message_sender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='allowed',
            field=models.ManyToManyField(blank=True, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='muted_by',
            field=models.ManyToManyField(blank=True, related_name='muted_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='seen_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
