# Generated by Django 3.2.18 on 2023-04-16 00:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputation', models.SmallIntegerField(default=0, null=True)),
                ('polecajacy', models.CharField(editable=False, max_length=64, null=True)),
                ('data_przyjecia', models.DateField(editable=False, null=True)),
                ('foto', models.ImageField(blank=True, default='obywatele/anonymous.png', null=True, upload_to='obywatele', verbose_name='Foto')),
                ('phone', models.CharField(blank=True, help_text='Phone number i.e. +48 123 456 789', max_length=72, null=True, verbose_name='Phone number')),
                ('city', models.CharField(blank=True, help_text='Where one spend most of their time', max_length=72, null=True, verbose_name='City')),
                ('responsibilities', models.CharField(blank=True, help_text='Tasks performed in our group', max_length=622, null=True, verbose_name='Responsibilities')),
                ('hobby', models.CharField(blank=True, help_text='Hobbies one have', max_length=622, null=True, verbose_name='Hobby')),
                ('to_give_away', models.CharField(blank=True, help_text='Things you are willing to give away for free', max_length=622, null=True, verbose_name='To give away')),
                ('to_borrow', models.CharField(blank=True, help_text='Stuff you can borrow to others', max_length=622, null=True, verbose_name='To borrow')),
                ('for_sale', models.CharField(blank=True, help_text='Stuff you have for sale', max_length=622, null=True, verbose_name='For sale')),
                ('i_need', models.CharField(blank=True, help_text='What do you need', max_length=622, null=True, verbose_name='I need')),
                ('skills', models.CharField(blank=True, help_text='Practical skills one have', max_length=622, null=True, verbose_name='Skills')),
                ('knowledge', models.CharField(blank=True, help_text='Knowledge one have', max_length=622, null=True, verbose_name='Knowledge')),
                ('want_to_learn', models.CharField(blank=True, help_text='Things one would like to learn', max_length=622, null=True, verbose_name='I want to learn')),
                ('business', models.CharField(blank=True, help_text='If running a business', max_length=622, null=True, verbose_name='Business')),
                ('job', models.CharField(blank=True, help_text='Profession', max_length=622, null=True, verbose_name='Job')),
                ('gift', models.CharField(blank=True, help_text='What gift would you like to receive', max_length=622, null=True, verbose_name='Gift')),
                ('other', models.CharField(blank=True, help_text='Other things worth mentioning', max_length=622, null=True, verbose_name='Other')),
                ('last_broadcast', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('uid', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'Citizen',
                'verbose_name_plural': 'Citizens',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.SmallIntegerField(default=0, null=True)),
                ('kandydat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kandydat', to='obywatele.uzytkownik')),
                ('obywatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obywatel', to='obywatele.uzytkownik')),
            ],
            options={
                'unique_together': {('kandydat', 'obywatel')},
            },
        ),
    ]
