# Generated by Django 3.2.18 on 2023-11-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='communicator',
            field=models.CharField(blank=True, help_text='Type communicator your are using hear and your phone/nick name. In case of FaceBook please paste link to your profile.', max_length=622, null=True, verbose_name='Communicator'),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='why',
            field=models.CharField(blank=True, help_text='In your own words please explain why do you want join our group', max_length=662, null=True, verbose_name='Why are you joining?'),
        ),
    ]
