# Generated by Django 3.2.18 on 2023-11-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0002_auto_20231112_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='why',
            field=models.CharField(blank=True, help_text='In your own words please explain why do you want join our group', max_length=662, null=True, verbose_name='Why do you want to join?'),
        ),
    ]
