# Generated by Django 3.2.18 on 2023-11-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0003_alter_uzytkownik_why'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='communicator',
            field=models.CharField(blank=True, help_text='Type here communicator your are using and your communicator nickname. In case of FaceBook please paste a link to your profile.', max_length=622, null=True, verbose_name='Communicator'),
        ),
    ]
