# Generated by Django 3.2.18 on 2023-11-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0004_alter_uzytkownik_communicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkownik',
            name='communicator',
        ),
    ]
