# Generated by Django 3.2.18 on 2023-12-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0005_remove_uzytkownik_communicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkownik',
            name='foto',
        ),
    ]
