# Generated by Django 5.0.6 on 2024-11-26 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0006_remove_uzytkownik_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='last_broadcast',
            field=models.DateTimeField(default=datetime.datetime(1899, 12, 31, 22, 36, tzinfo=datetime.timezone.utc)),
        ),
    ]
