# Generated by Django 3.2.18 on 2023-04-16 00:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('author', models.CharField(blank=True, max_length=200, null=True, verbose_name='Author')),
                ('cover', models.ImageField(blank=True, default='elibrary/default.png', help_text='Cover proportions should be 2/3. I.E. width x 1.5 = height', null=True, upload_to='elibrary', verbose_name='Cover')),
                ('file_epub', models.FileField(blank=True, null=True, upload_to='elibrary', validators=[django.core.validators.FileExtensionValidator(['epub'])], verbose_name='epub')),
                ('file_mobi', models.FileField(blank=True, null=True, upload_to='elibrary', validators=[django.core.validators.FileExtensionValidator(['mobi'])], verbose_name='mobi')),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='elibrary', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='pdf')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'eBooks',
                'ordering': ('id',),
            },
        ),
    ]
