# Generated by Django 3.2.18 on 2023-04-30 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='uploaded',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='Uploaded'),
        ),
    ]
