# Generated by Django 5.2.9 on 2026-02-12 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0005_alter_book_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Uploaded'),
        ),
    ]
