# Generated by Django 5.0.6 on 2025-04-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_post_is_pinned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_pinned',
            new_name='is_important',
        ),
        migrations.AlterField(
            model_name='post',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='Important'),
        ),
    ]
